[project]
name = "polygraph"
version = "0.1.1"
description = "A multiplayer party game bot for Telegram (inspired by the classic Spyfall mechanics)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.13.0",
    "pydantic-settings>=2.0.0",
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.0",
    "python-dotenv>=1.0.0",
]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[tool.bandit]
exclude_dirs = [".venv", "tests"]
skips = [
    "B311",
    "B110",
    "B104",
]
